name: matrix_rotate_arbitrary_axis
description: Library to generate rotation matrix around arbitrary axis
version: 1.0.0
homepage: https://github.com/orestesgaolin/animated_flutter_logo

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter