name: matrix_rotate_arbitrary_axis
description: Simple library to generate rotation matrix around arbitrary axis
version: 1.0.1
homepage: https://github.com/orestesgaolin/matrix_rotate_arbitrary_axis

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  vector_math: ^2.0.8

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter
