name: matrix_rotate_arbitrary_axis
description: Simple library to generate rotation matrix around arbitrary axis
version: 1.1.0
homepage: https://github.com/orestesgaolin/matrix_rotate_arbitrary_axis

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
